import {randomUUID,randomInt} from 'node:crypto';
import {cases,findCase,publicCase,solutionSummary} from './cases.js';
import {isCorrect} from './ai.js';
export class GameError extends Error {constructor(message,status=400){super(message);this.status=status}}
export const WRONG_MESSAGE='오답입니다. 진실 아직 밝혀지지 않았습니다';
export function createGames(db,ai){
  async function owned(id,uid){const g=await db.one('SELECT * FROM games WHERE id=$1 AND streamer_id=$2',[id,uid]);if(!g)throw new GameError('사건을 찾을 수 없습니다.',404);return g}
  const history=id=>db.all('SELECT id,question,verdict,created_at FROM questions WHERE game_id=$1 ORDER BY created_at,id',[id]);
  const attempts=id=>db.all('SELECT * FROM attempts WHERE game_id=$1 ORDER BY created_at,id',[id]);
  async function state(id,uid){const g=await owned(id,uid),a=await attempts(id);return {id:g.id,status:g.status,createdAt:Number(g.created_at),case:publicCase(findCase(g.case_id)),questions:await history(id),attempts:a.map(x=>({answer:x.answer,correct:!!x.correct,createdAt:Number(x.created_at)})),attemptsLeft:Math.max(0,3-a.length),report:g.report?JSON.parse(g.report):null,finalAnswer:g.status==='completed'?g.final_answer:null,solution:g.status==='completed'?solutionSummary(findCase(g.case_id)):null,solved:g.status==='completed'&&!!a.at(-1)?.correct,maxQuestions:40}}
  async function claim(id,uid,status){const op=randomUUID();const r=await db.run("UPDATE games SET status=$1,operation_id=$2,lock_until=$3 WHERE id=$4 AND streamer_id=$5 AND (status='active' OR (status IN ('asking','grading') AND lock_until<$6))",[status,op,Date.now()+180000,id,uid,Date.now()]);if(!r.changes)throw new GameError('다른 질문 또는 답안을 처리 중입니다. 잠시 후 다시 시도하세요.',409);return op}
  const release=(id,op)=>db.run("UPDATE games SET status='active',operation_id=NULL,lock_until=0 WHERE id=$1 AND operation_id=$2 AND status<>'completed'",[id,op]);
  const result=(a,count,complete)=>({correct:!!a.correct,completed:complete,attemptsLeft:3-count,message:a.correct?'정답입니다. 사건의 진실을 밝혀냈습니다.':WRONG_MESSAGE});
  return {owned,history,attempts,state,
    async start(uid){return db.transaction(async tx=>{await tx.run('UPDATE streamers SET name=name WHERE id=$1',[uid]);const active=await tx.one("SELECT id FROM games WHERE streamer_id=$1 AND status<>'completed'",[uid]);if(active)return active.id;const played=await tx.all('SELECT case_id FROM games WHERE streamer_id=$1',[uid]);const pool=cases.filter(c=>!played.some(p=>p.case_id===c.id));if(!pool.length)throw new GameError('10개의 사건을 모두 수사했습니다. 기록 보관함에서 분석지를 확인하세요.',409);const id=randomUUID();await tx.run("INSERT INTO games(id,streamer_id,case_id,status,created_at) VALUES($1,$2,$3,'active',$4)",[id,uid,pool[randomInt(pool.length)].id,Date.now()]);return id})},
    async ask(id,uid,question,requestId){const g=await owned(id,uid);const prior=await db.one('SELECT question,verdict FROM questions WHERE game_id=$1 AND request_id=$2',[id,requestId]);if(prior){if(prior.question!==question)throw new GameError('요청 식별자가 이미 사용됐습니다.',409);return prior}if(g.status==='completed')throw new GameError('이미 종료된 사건입니다.',409);const op=await claim(id,uid,'asking');try{const h=await history(id);if(h.length>=40)throw new GameError('질문 40회를 모두 사용했습니다. 사건 해석을 제출하세요.',409);const answer=await ai.ask(findCase(g.case_id),h,question);await db.transaction(async tx=>{const row=await tx.one('SELECT operation_id FROM games WHERE id=$1',[id]);if(row.operation_id!==op)throw new GameError('요청 시간이 만료되었습니다.',409);await tx.run('INSERT INTO questions(id,game_id,request_id,question,verdict,created_at) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),id,requestId,question,answer.verdict,Date.now()]);await tx.run("UPDATE games SET status='active',operation_id=NULL,lock_until=0 WHERE id=$1",[id])});return {question,...answer}}finally{await release(id,op)}},
    async submit(id,uid,answer,requestId){const g=await owned(id,uid),existing=await attempts(id),prior=existing.find(a=>a.request_id===requestId);if(prior){if(prior.answer!==answer)throw new GameError('요청 식별자가 이미 사용됐습니다.',409);return result(prior,existing.length,g.status==='completed')}
      if(g.status==='completed')throw new GameError('이미 종료된 사건입니다.',409);const op=await claim(id,uid,'grading');try{const previous=await attempts(id);if(previous.length>=3)throw new GameError('제출 기회를 모두 사용했습니다.',409);const report=await ai.analyze(findCase(g.case_id),await history(id),answer,previous);const correct=isCorrect(report),complete=correct||previous.length===2;
        await db.transaction(async tx=>{const row=await tx.one('SELECT operation_id FROM games WHERE id=$1',[id]);if(row.operation_id!==op)throw new GameError('요청 시간이 만료되었습니다.',409);await tx.run('INSERT INTO attempts(id,game_id,request_id,answer,correct,report,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),id,requestId,answer,correct?1:0,JSON.stringify(report),Date.now()]);if(complete)await tx.run("UPDATE games SET status='completed',final_answer=$1,report=$2,score=$3,grade=$4,finished_at=$5,operation_id=NULL,lock_until=0 WHERE id=$6",[answer,JSON.stringify(report),report.score,report.grade,Date.now(),id]);else await tx.run("UPDATE games SET status='active',operation_id=NULL,lock_until=0 WHERE id=$1",[id])});return result({correct},previous.length+1,complete);
      }finally{await release(id,op)}},
    async list(uid){const rows=await db.all('SELECT id,case_id,status,created_at,score,grade FROM games WHERE streamer_id=$1 ORDER BY created_at DESC',[uid]);return Promise.all(rows.map(async g=>{const a=await attempts(g.id);return {...g,title:findCase(g.case_id).title,attemptCount:a.length,wrongCount:a.filter(x=>!x.correct).length,solved:!!a.at(-1)?.correct}}))},
    async ranking(){return db.all("SELECT s.id,s.name,COUNT(g.id) AS games,SUM(g.score) AS points,ROUND(AVG(g.score),1) AS average,MAX(g.score) AS best,SUM(CASE WHEN EXISTS(SELECT 1 FROM attempts a WHERE a.game_id=g.id AND a.correct=1) THEN 1 ELSE 0 END) AS solved FROM streamers s JOIN games g ON g.streamer_id=s.id WHERE s.verified=1 AND g.status='completed' GROUP BY s.id,s.name ORDER BY points DESC,solved DESC,average DESC,s.id LIMIT 100")}
  };
}
