import express from 'express';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readFile} from 'node:fs/promises';
import {randomBytes,createHash} from 'node:crypto';
import {z} from 'zod';
import {openDatabase} from './db.js';
import {createAI,migrateStoredGrades,voicesForModel} from './ai.js';
import {createGames,GameError} from './game.js';
import {cases,publicCase} from './cases.js';
import {chzzkRequest} from './chzzk.js';
export function configuration(env=process.env){
  const production=env.NODE_ENV==='production';if(production&&(!env.SESSION_SECRET||env.SESSION_SECRET.length<32))throw new Error('Set SESSION_SECRET to at least 32 characters');if(production&&!env.DATABASE_URL)throw new Error('Set DATABASE_URL to Railway PostgreSQL');const base=new URL(env.PUBLIC_URL||`http://localhost:${env.PORT||3000}`);if(production&&base.protocol!=='https:')throw new Error('PUBLIC_URL must use HTTPS');if(production&&(env.MOCK_AI==='true'||env.ALLOW_DEV_LOGIN==='true'))throw new Error('Disable test modes in production');return {production,base:base.origin,port:Number(env.PORT||3000),secret:env.SESSION_SECRET||'local-development-not-for-production',apiKey:env.OPENAI_API_KEY,model:env.OPENAI_MODEL||'gpt-5.6-sol',ttsModel:env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts',ttsVoice:env.OPENAI_TTS_VOICE||'onyx',chzzkId:env.CHZZK_CLIENT_ID,chzzkSecret:env.CHZZK_CLIENT_SECRET,googleVerification:env.GOOGLE_SITE_VERIFICATION||'',allowDev:!production&&env.ALLOW_DEV_LOGIN==='true',mock:!production&&env.MOCK_AI==='true',allowed:(env.ALLOWED_CHANNEL_IDS||'').split(',').map(s=>s.trim()).filter(Boolean)};
}
const hash=s=>createHash('sha256').update(s).digest('hex');
function cookie(req,name){return(req.headers.cookie||'').split(';').map(p=>p.trim()).find(p=>p.startsWith(`${name}=`))?.slice(name.length+1)||''}
export async function createApp({config=configuration(),db,ai}={}){
  db||=await openDatabase();await migrateStoredGrades(db);ai||=createAI(config);const app=express(),games=createGames(db,ai),cookieOptions={httpOnly:true,secure:config.production,sameSite:'lax',path:'/',maxAge:7*86400000};
  const dist=fileURLToPath(new URL('../dist/',import.meta.url)),seoJson=JSON.stringify({'@context':'https://schema.org','@type':'WebApplication',name:'프로파일러: AI 추리 사건실',url:`${config.base}/`,description:'AI에게 질문하며 10개의 미스터리 사건을 재구성하는 무료 서술형 웹 추리게임',applicationCategory:'GameApplication',operatingSystem:'Web',inLanguage:'ko-KR',isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'KRW'}}),seoHash=createHash('sha256').update(seoJson).digest('base64');
  const verification=/^[A-Za-z0-9_-]{8,200}$/.test(config.googleVerification)?`<meta name="google-site-verification" content="${config.googleVerification}">`:'';
  const indexPage=(await readFile(path.join(dist,'index.html'),'utf8')).replaceAll('__PUBLIC_URL__',config.base).replace('__SEO_JSON_LD__',seoJson).replace('<!-- GOOGLE_SITE_VERIFICATION -->',verification);
  app.disable('x-powered-by');app.set('trust proxy',1);app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'SAMEORIGIN','Content-Security-Policy':`default-src 'self'; script-src 'self' 'sha256-${seoHash}'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; media-src 'self' blob:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'self'`});if(config.production)res.set('Strict-Transport-Security','max-age=31536000');next()});app.use(express.json({limit:'24kb'}));
  app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(req.method!=='GET'&&(req.get('origin')!==config.base||!req.is('application/json')))return res.status(403).json({error:'같은 사이트에서 요청해 주세요.'});next()});
  const limits=new Map();const limit=(key,max,window=60000)=>{const now=Date.now(),s=limits.get(key);if(!s||s.until<now){limits.set(key,{count:1,until:now+window});return}if(s.count>=max)throw new GameError('요청이 많습니다. 잠시 후 다시 시도하세요.',429);s.count++};const cleanup=setInterval(()=>{for(const[k,v]of limits)if(v.until<Date.now())limits.delete(k);void Promise.all([db.run('DELETE FROM sessions WHERE expires_at<$1',[Date.now()]),db.run('DELETE FROM oauth_states WHERE expires_at<$1',[Date.now()])]).catch(()=>{})},60000);cleanup.unref();
  app.get('/health',async(req,res)=>{try{await db.one('SELECT 1 AS ok');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
  app.get('/robots.txt',(req,res)=>res.type('text/plain').send(`User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /auth/\nSitemap: ${config.base}/sitemap.xml\n`));
  app.get('/sitemap.xml',(req,res)=>{const images=cases.map(c=>`<image:image><image:loc>${config.base}/images/${c.id}.png</image:loc><image:title>${c.title} 사건 현장 재현</image:title></image:image>`).join('');res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"><url><loc>${config.base}/</loc>${images}</url></urlset>`)});
  async function user(req){const token=cookie(req,'profiler_session');if(!token)return null;return await db.one('SELECT s.id,s.name,s.verified FROM sessions a JOIN streamers s ON s.id=a.streamer_id WHERE a.id=$1 AND a.expires_at>$2',[hash(token),Date.now()])||null}
  async function auth(req,res,next){req.user=await user(req);if(!req.user)throw new GameError('치지직 로그인이 필요합니다.',401);if(config.allowed.length&&!config.allowed.includes(req.user.id)&&req.user.verified)throw new GameError('참여 허용된 채널이 아닙니다.',403);next()}
  async function session(uid,res){const token=randomBytes(32).toString('base64url');await db.run('INSERT INTO sessions(id,streamer_id,expires_at) VALUES($1,$2,$3)',[hash(token),uid,Date.now()+7*86400000]);res.cookie('profiler_session',token,cookieOptions)}
  app.get('/auth/chzzk',async(req,res)=>{limit(`auth:${req.ip}`,20);if(!config.chzzkId||!config.chzzkSecret)return res.redirect('/?authError=setup');const state=randomBytes(32).toString('base64url');await db.run('INSERT INTO oauth_states(id,expires_at) VALUES($1,$2)',[hash(state),Date.now()+600000]);res.cookie('profiler_oauth',state,{...cookieOptions,maxAge:600000});const url=new URL('https://chzzk.naver.com/account-interlock');url.search=new URLSearchParams({clientId:config.chzzkId,redirectUri:`${config.base}/auth/chzzk/callback`,state}).toString();res.redirect(url.toString())});
  app.get('/auth/chzzk/callback',async(req,res)=>{res.set('Cache-Control','no-store');const{state,code}=req.query;if(typeof state!=='string'||typeof code!=='string'||state!==cookie(req,'profiler_oauth'))return res.redirect('/?authError=state');res.clearCookie('profiler_oauth',{httpOnly:true,secure:config.production,sameSite:'lax',path:'/'});const removed=await db.run('DELETE FROM oauth_states WHERE id=$1 AND expires_at>$2',[hash(state),Date.now()]);if(!removed.changes)return res.redirect('/?authError=state');try{const token=await chzzkRequest('/auth/v1/token',{body:{grantType:'authorization_code',clientId:config.chzzkId,clientSecret:config.chzzkSecret,code,state}});if(!token.accessToken)throw new Error('Invalid token');const p=await chzzkRequest('/open/v1/users/me',{token:token.accessToken});if(typeof p.channelId!=='string'||typeof p.channelName!=='string')throw new Error('Invalid profile');if(config.allowed.length&&!config.allowed.includes(p.channelId))return res.redirect('/?authError=not_allowed');await db.run('INSERT INTO streamers(id,name,verified,created_at) VALUES($1,$2,1,$3) ON CONFLICT(id) DO UPDATE SET name=excluded.name,verified=1',[p.channelId,p.channelName,Date.now()]);const old=cookie(req,'profiler_session');if(old)await db.run('DELETE FROM sessions WHERE id=$1',[hash(old)]);await session(p.channelId,res);return res.redirect('/')}catch{return res.redirect('/?authError=connection')}});
  app.post('/api/dev-login',async(req,res)=>{if(!config.allowDev)throw new GameError('지원하지 않는 경로입니다.',404);limit(`dev:${req.ip}`,10);await db.run('INSERT INTO streamers(id,name,verified,created_at) VALUES($1,$2,0,$3) ON CONFLICT(id) DO NOTHING',['dev-local','로컬 테스트 수사관',Date.now()]);await session('dev-local',res);res.json({ok:true})});
  app.post('/api/logout',auth,async(req,res)=>{await db.run('DELETE FROM sessions WHERE id=$1',[hash(cookie(req,'profiler_session'))]);res.clearCookie('profiler_session',{httpOnly:true,secure:config.production,sameSite:'lax',path:'/'});res.json({ok:true})});
  app.get('/api/me',async(req,res)=>res.json({user:await user(req),configured:{ai:!!config.apiKey||config.mock,chzzk:!!config.chzzkId&&!!config.chzzkSecret},dev:config.allowDev,mock:config.mock,tts:{voices:voicesForModel(config.ttsModel),defaultVoice:config.ttsVoice}}));
  app.get('/api/catalog',(req,res)=>res.json({cases:cases.map(publicCase)}));
  app.get('/api/games',auth,async(req,res)=>res.json({games:await games.list(req.user.id),totalCases:10}));
  app.post('/api/games',auth,async(req,res)=>{limit(`start:${req.user.id}`,15);const id=await games.start(req.user.id);res.json(await games.state(id,req.user.id))});
  app.get('/api/games/:id',auth,async(req,res)=>res.json(await games.state(req.params.id,req.user.id)));
  app.get('/api/games/:id/hints/:number',auth,async(req,res)=>{limit(`hint:${req.user.id}`,20);const number=z.coerce.number().int().min(1).max(2).parse(req.params.number);res.json(await games.hint(req.params.id,req.user.id,number))});
  app.post('/api/games/:id/questions',auth,async(req,res)=>{limit(`ask:${req.user.id}`,15);const b=z.object({question:z.string().trim().min(2).max(600),requestId:z.string().uuid()}).parse(req.body);res.json(await games.ask(req.params.id,req.user.id,b.question,b.requestId))});
  app.post('/api/games/:id/submit',auth,async(req,res)=>{limit(`submit:${req.user.id}`,6);const b=z.object({answer:z.string().trim().min(10).max(5000),requestId:z.string().uuid()}).parse(req.body);res.json(await games.submit(req.params.id,req.user.id,b.answer,b.requestId))});
  app.get('/api/tts/:verdict',auth,async(req,res)=>{limit(`tts:${req.user.id}`,45);res.type('audio/mpeg').send(await ai.speech(req.params.verdict,req.query.voice?z.enum(voicesForModel(config.ttsModel)).parse(req.query.voice):config.ttsVoice))});
  app.get('/api/rankings',async(req,res)=>{limit(`rank:${req.ip}`,60);res.json({rankings:await games.ranking()})});
  app.use('/api',(req,res)=>res.status(404).json({error:'요청한 기능을 찾을 수 없습니다.'}));app.get(['/', '/index.html'],(req,res)=>res.type('html').send(indexPage));app.use(express.static(dist,{index:false}));
  app.use((err,req,res,next)=>{if(res.headersSent)return next(err);const status=err instanceof z.ZodError?400:err.status||500;res.status(status).json({error:err instanceof z.ZodError?'입력 길이와 형식을 확인해 주세요.':status<500||err.status?err.message:'서버 오류가 발생했습니다. 잠시 후 다시 시도하세요.'})});
  return {app,db,games,async close(){clearInterval(cleanup);await db.close()}};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const config=configuration(),runtime=await createApp({config});const server=runtime.app.listen(config.port,'0.0.0.0',()=>console.log(`Profiler ready at ${config.base} (${runtime.db.kind}${config.mock?', MOCK AI':''})`));const stop=()=>{server.close(()=>void runtime.close().then(()=>process.exit(0)));server.closeAllConnections();setTimeout(()=>process.exit(0),5000).unref()};process.on('SIGTERM',stop);process.on('SIGINT',stop)}
